options:
  logging: CLOUD_LOGGING_ONLY  # Fixes Cloud Build logging issue

substitutions:
  _REGION: asia-east1
  _PROJECT_ID: predictive-maintenance-448107
  _REPOSITORY_NAME: mlops

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'dockerfile_fastapi'  # Ensure this matches your actual Dockerfile name
      - '-t'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/predictive-maintenance:$COMMIT_SHA'
      - '-t'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/predictive-maintenance:latest'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/predictive-maintenance:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/predictive-maintenance:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'predictive-maintenance-service'
      - '--image'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/predictive-maintenance:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
      - '--port'
      - '8080' 