# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .
COPY requirements_2.txt /app/requirements_2.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements_2.txt

# Expose the FastAPI port
EXPOSE 8000

# Run FastAPI using Uvicorn
CMD ["uvicorn", "app1:app", "--host", "0.0.0.0", "--port", "8080"]
