# Use official Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
RUN pip install mlflow gunicorn

# Expose Cloud Run's default port (8080)
EXPOSE 8080

# Run MLflow UI using Cloud Run's assigned port
CMD mlflow server --host 0.0.0.0 --port ${PORT} --backend-store-uri sqlite:///mlflow.db --default-artifact-root gs://your-gcs-bucket/mlflow/

